name: Build Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Test TypeScript compilation
      run: npm run check

    - name: Test build process
      run: npm run build

    - name: Verify build artifacts
      run: |
        if [ ! -d "dist" ]; then
          echo "Build directory 'dist' not found!"
          exit 1
        fi
        if [ ! -f "dist/index.js" ]; then
          echo "Built server file 'dist/index.js' not found!"
          exit 1
        fi
        if [ ! -d "dist/public" ]; then
          echo "Built client directory 'dist/public' not found!"
          exit 1
        fi
        echo "✅ All build artifacts found"

    - name: Test application start (dry run)
      run: |
        # Test that the built application can start without errors
        timeout 10s node dist/index.js || [ $? -eq 124 ]
        echo "✅ Application starts successfully"